package ProjectEuler;

public class ProblemTwo {

	/**
	 * Scott Hochman
	 * 07/24/2013
	 * 
	 * Problem:
	 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
     * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	 */
	public static void main(String[] args) {
		long now = System.currentTimeMillis();
		int firstValue = 1;
		int secondValue = 2;
		int sum = 0;
		while(secondValue <= 4000000) {
			if( (secondValue % 2) == 0) {
				sum += secondValue;
			}
			int tmp = secondValue;
			secondValue += firstValue;
			firstValue = tmp;
		}
		System.out.println("Sum: " + sum);
		System.out.println("Completed in " + (System.currentTimeMillis() - now) + " ms.");
	}

}
